[build]
command = "yarn build --environment=staging"
environment = { NODE_VERSION = "12.18.4" }

[context.master]
command = "yarn build --environment=production"
environment = { NODE_VERSION = "12.18.4" }

