[build]
command = "yarn build"

[context.develop]
command = "CARTO_USER=dcpadmin API_HOST=https://layers-api-staging.planninglabs.nyc yarn build --environment=staging"

[context.data-qa]
command = "CARTO_USER=dcpadmin API_HOST=https://layers-api-data.planninglabs.nyc yarn build --environment=staging"

[context.master]
command = "CARTO_USER=planninglabs API_HOST=https://layers-api.planninglabs.nyc yarn build --environment=production"
