[build]
command = "yarn build"

[context.develop]
command = "yarn build --environment=development"

[context.develop.environment]
API_HOST="https://layers-api-staging.planninglabs.nyc"
CARTO_USER="dcpadmin"

[context.data-qa]

[context.data-qa.environment]
API_HOST="https://layers-api-data.planninglabs.nyc"
CARTO_USER="dcpadmin"

[context.production]

[context.production.environment]
API_HOST="https://layers-api.planninglabs.nyc"
CARTO_USER="planninglabs"
