[build]
command = "yarn build --environment=staging"
environment = { NODE_VERSION = "12.18.4" }

[context.data-qa]
command = "yarn build --environment=staging"
environment = {NODE_VERSION = "12.18.4", LAYERS_API_URL = "layers-api-data.planninglabs.nyc"}

[context.master]
command = "yarn build --environment=production"
environment = { NODE_VERSION = "12.18.4" }